Repository stfc/janus-core, pull requests merged in 2024-06, with the labels that each got.

#177 Temporarily pin ASE version
  pyproject.toml
Labels: janus

#179 Allow strings for optimization function names
  janus_core/calculations/geom_opt.py
  janus_core/cli/geomopt.py
  tests/test_geom_opt.py
  tests/test_geomopt_cli.py
  tests/test_phonons_cli.py
Labels: enhancement, janus

#181 Update ASE
  README.md
  janus_core/calculations/geom_opt.py
  pyproject.toml
  tests/test_eos_cli.py
  tests/test_geom_opt.py
  tests/test_geomopt_cli.py
  tests/test_single_point.py
  tests/test_singlepoint_cli.py
Labels: bug, janus

#176 name ML properties in the results file by architecture, energy become…
  janus_core/calculations/single_point.py
  tests/test_single_point.py
  tests/test_singlepoint_cli.py
Labels: janus

#183 remove nans for real now
  janus_core/calculations/single_point.py
Labels: bug

#174 Add VAF and RDF computation
  docs/source/apidoc/janus_core.rst
  janus_core/calculations/md.py
  janus_core/cli/md.py
  janus_core/cli/types.py
  janus_core/helpers/janus_types.py
  janus_core/helpers/post_process.py
  tests/data/lj-traj.xyz
  tests/test_md.py
  tests/test_post_process.py
Labels: enhancement

#190 Block numpy 2.0 as dependency
  pyproject.toml
Labels: bug, janus

#191 Add tutorials
  README.md
  docs/source/user_guide/tutorial.rst
Labels: documentation, janus

#192 Promote CHGNET and M3GNET to full dependencies
  pyproject.toml
  tests/test_eos.py
  tests/test_mlip_calculators.py
  tests/test_single_point.py
Labels: enhancement, janus
