Repository stfc/janus-core, pull requests merged in 2024-11, with the labels that each got.

#341 Restructure helpers directory
  docs/source/apidoc/janus_core.rst
  docs/source/developer_guide/tutorial.rst
  janus_core/calculations/base.py
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/single_point.py
  janus_core/cli/train.py
  janus_core/helpers/mlip_calculators.py
  janus_core/helpers/struct_io.py
  janus_core/helpers/utils.py
  janus_core/processing/correlator.py
  janus_core/processing/observables.py
  janus_core/processing/post_process.py
  janus_core/processing/symmetry.py
  janus_core/training/train.py
  tests/test_correlator.py
  tests/test_post_process.py
  tests/test_utils.py
Labels: documentation

#318 Add lags to vafs
  janus_core/processing/post_process.py
  tests/test_post_process.py
Labels: enhancement

#320 Add support for non-diagonal supercells
  docs/source/user_guide/command_line.rst
  janus_core/calculations/phonons.py
  janus_core/cli/phonons.py
  tests/test_phonons_cli.py
Labels: enhancement

#348 Update docstrings
  janus_core/calculations/base.py
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/phonons.py
  janus_core/calculations/single_point.py
  janus_core/helpers/log.py
  janus_core/helpers/mlip_calculators.py
  janus_core/helpers/struct_io.py
  janus_core/helpers/utils.py
  janus_core/processing/post_process.py
  janus_core/training/train.py
  tests/utils.py
Labels: documentation

#329 Refactor phonons
  .gitignore
  docs/source/images/NaCl-bands.svg
  docs/source/user_guide/command_line.rst
  janus_core/calculations/phonons.py
  janus_core/cli/phonons.py
  janus_core/cli/types.py
  tests/data/paths.yml
  tests/test_phonons.py
  tests/test_phonons_cli.py
Labels: enhancement

#336 Save model info
  README.md
  docs/source/user_guide/command_line.rst
  docs/source/user_guide/python.rst
  janus_core/helpers/mlip_calculators.py
  janus_core/helpers/struct_io.py
  tests/test_mlip_calculators.py
  tests/test_singlepoint_cli.py
  tests/test_utils.py
Labels: enhancement

#354 Update ruff
  .pre-commit-config.yaml
  pyproject.toml
Labels: bug, enhancement, testing

#355 Update README
  README.md
Labels: documentation

#285 Adds Velocity, ShearStress, StressDiagonal, observables
  docs/source/apidoc/janus_core.rst
  docs/source/conf.py
  docs/source/developer_guide/tutorial.rst
  janus_core/helpers/janus_types.py
  janus_core/helpers/utils.py
  janus_core/processing/correlator.py
  janus_core/processing/observables.py
  janus_core/processing/post_process.py
  tests/test_correlator.py
  tests/test_utils.py
Labels: enhancement
