Repository stfc/janus-core, pull requests merged in 2024-08, with the labels that each got.

#232 Fix matgl
  pyproject.toml
Labels: bug, janus

#229 Add table writer to utils for standard format tables
  docs/source/conf.py
  janus_core/helpers/utils.py
Labels: enhancement, janus

#236 Update sevenn
  pyproject.toml
  tests/test_single_point.py
Labels: bug, janus

#238 Add version for sevennet
  janus_core/helpers/mlip_calculators.py
  release.sh
Labels: documentation, janus

#244 Delete duplicate struct from CLI summary
  janus_core/cli/utils.py
Labels: bug, enhancement

#243 Rename geomopt flags
  README.md
  janus_core/cli/geomopt.py
  tests/test_geomopt_cli.py
Labels: documentation, enhancement, janus

#247 Fix calculator copies
  janus_core/calculations/eos.py
  janus_core/calculations/single_point.py
Labels: bug, janus

#248 Fix write
  janus_core/helpers/utils.py
  tests/test_singlepoint_cli.py
Labels: bug, janus

#249 Add descriptor per atom
  janus_core/calculations/descriptors.py
  janus_core/cli/descriptors.py
  tests/test_descriptors.py
  tests/test_descriptors_cli.py
Labels: enhancement, janus

#225 Tidy calculations
  .gitignore
  README.md
  docs/source/conf.py
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/phonons.py
  janus_core/calculations/single_point.py
  janus_core/cli/descriptors.py
  janus_core/cli/eos.py
  janus_core/cli/geomopt.py
  janus_core/cli/md.py
  janus_core/cli/phonons.py
  janus_core/cli/singlepoint.py
  janus_core/cli/utils.py
  janus_core/helpers/janus_types.py
  janus_core/helpers/mlip_calculators.py
  janus_core/helpers/utils.py
  tests/test_correlator.py
  tests/test_descriptors.py
  tests/test_eos.py
  tests/test_filenamemixin.py
  tests/test_geom_opt.py
  tests/test_md.py
  tests/test_md_cli.py
  tests/test_mlip_calculators.py
  tests/test_phonons.py
  tests/test_phonons_cli.py
  tests/test_post_process.py
  tests/test_single_point.py
  tests/test_utils.py
Labels: enhancement, janus

#227 Update documentation
  README.md
  docs/source/conf.py
  docs/source/developer_guide/get_started.rst
  docs/source/developer_guide/tutorial.rst
  docs/source/getting_started/getting_started.rst
  docs/source/index.rst
  docs/source/user_guide/command_line.rst
  docs/source/user_guide/get_started.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/python.rst
  docs/source/user_guide/tutorial.rst
  pyproject.toml
Labels: documentation

#254 Add ruff
  .pre-commit-config.yaml
  docs/source/conf.py
  docs/source/developer_guide/get_started.rst
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/phonons.py
  janus_core/calculations/single_point.py
  janus_core/cli/descriptors.py
  janus_core/cli/eos.py
  janus_core/cli/geomopt.py
  janus_core/cli/md.py
  janus_core/cli/phonons.py
  janus_core/cli/singlepoint.py
  janus_core/cli/types.py
  janus_core/cli/utils.py
  janus_core/helpers/correlator.py
  janus_core/helpers/janus_types.py
  janus_core/helpers/mlip_calculators.py
  janus_core/helpers/observables.py
  janus_core/helpers/post_process.py
  janus_core/helpers/stats.py
  janus_core/helpers/utils.py
  pyproject.toml
  tests/test_correlator.py
  tests/test_filenamemixin.py
  tests/test_geom_opt.py
  tests/test_geomopt_cli.py
  tests/test_md.py
  tests/test_md_cli.py
  tests/test_phonons_cli.py
  tests/test_post_process.py
  tests/test_singlepoint_cli.py
  tests/test_train_cli.py
  tests/test_utils.py
Labels: testing

#271 Remove ANSI sequences from stdout in tests
  tests/test_cli.py
  tests/test_descriptors_cli.py
  tests/test_eos_cli.py
  tests/test_geomopt_cli.py
  tests/test_md_cli.py
  tests/test_phonons_cli.py
  tests/test_singlepoint_cli.py
  tests/test_train_cli.py
  tests/utils.py
Labels: bug, testing, priority

#266 Fix write params
  janus_core/helpers/utils.py
  tests/test_geom_opt.py
Labels: bug

#258 Add carbon emissions info and summary
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/phonons.py
  janus_core/calculations/single_point.py
  janus_core/cli/descriptors.py
  janus_core/cli/eos.py
  janus_core/cli/geomopt.py
  janus_core/cli/md.py
  janus_core/cli/phonons.py
  janus_core/cli/singlepoint.py
  janus_core/cli/utils.py
  tests/test_descriptors.py
  tests/test_descriptors_cli.py
  tests/test_eos.py
  tests/test_eos_cli.py
  tests/test_geom_opt.py
  tests/test_geomopt_cli.py
  tests/test_md.py
  tests/test_md_cli.py
  tests/test_phonons.py
  tests/test_phonons_cli.py
  tests/test_single_point.py
  tests/test_singlepoint_cli.py
Labels: enhancement

#256 Update MLIP installations
  .github/workflows/ci.yml
  README.md
  conftest.py
  docs/source/developer_guide/get_started.rst
  docs/source/developer_guide/tutorial.rst
  docs/source/getting_started/getting_started.rst
  pyproject.toml
  tox.ini
Labels: enhancement

#278 Auto write results
  janus_core/calculations/md.py
  janus_core/calculations/phonons.py
  tests/test_md_cli.py
  tests/test_phonons_cli.py
Labels: enhancement

#265 Add carbon emissions for training
  janus_core/cli/train.py
  janus_core/helpers/train.py
  tests/test_singlepoint_cli.py
  tests/test_train_cli.py
Labels: enhancement

#282 Update ALIGNN testing
  tests/test_mlip_calculators.py
  tests/test_single_point.py
Labels: bug, testing

#274 Fix post process issues
  janus_core/calculations/md.py
  janus_core/helpers/post_process.py
Labels: bug

#230 Use table writer in phonon/md
  janus_core/calculations/md.py
  janus_core/calculations/phonons.py
  janus_core/helpers/utils.py
  tests/test_md.py
  tests/test_md_cli.py
Labels: enhancement

#283 Add file inputs to all calculations
  README.md
  docs/source/apidoc/janus_core.rst
  janus_core/calculations/base.py
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/phonons.py
  janus_core/calculations/single_point.py
  janus_core/cli/descriptors.py
  janus_core/cli/eos.py
  janus_core/cli/geomopt.py
  janus_core/cli/md.py
  janus_core/cli/phonons.py
  janus_core/cli/singlepoint.py
  janus_core/cli/types.py
  janus_core/cli/utils.py
  janus_core/helpers/utils.py
  tests/test_filenamemixin.py
  tests/test_md_cli.py
Labels: enhancement, priority

#287 Fix MD file names
  janus_core/calculations/md.py
  tests/test_md_cli.py
Labels: bug, priority

#289 Remove duplicated descriptors log
  janus_core/calculations/descriptors.py
  tests/test_descriptors_cli.py
Labels: bug

#288 Fix summary duplication
  janus_core/cli/descriptors.py
  janus_core/cli/eos.py
  janus_core/cli/geomopt.py
  janus_core/cli/md.py
  janus_core/cli/phonons.py
  janus_core/cli/singlepoint.py
  janus_core/cli/utils.py
  janus_core/helpers/utils.py
  tests/test_utils.py
Labels: bug

#291 Fix set_calc default when reading structure file
  janus_core/helpers/utils.py
  tests/test_geomopt_cli.py
Labels: bug, priority

#294 Make directories when building filenames
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/phonons.py
  janus_core/calculations/single_point.py
  janus_core/helpers/utils.py
  tests/test_descriptors_cli.py
  tests/test_eos_cli.py
  tests/test_geomopt_cli.py
  tests/test_md_cli.py
  tests/test_phonons_cli.py
  tests/test_singlepoint_cli.py
Labels: enhancement

#280 Set consistent log and summary file names
  README.md
  docs/source/user_guide/command_line.rst
  janus_core/calculations/base.py
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/phonons.py
  janus_core/calculations/single_point.py
  janus_core/cli/descriptors.py
  janus_core/cli/eos.py
  janus_core/cli/geomopt.py
  janus_core/cli/md.py
  janus_core/cli/phonons.py
  janus_core/cli/singlepoint.py
  janus_core/cli/train.py
  janus_core/cli/types.py
  janus_core/helpers/train.py
  tests/test_descriptors_cli.py
  tests/test_eos_cli.py
  tests/test_geomopt_cli.py
  tests/test_md_cli.py
  tests/test_phonons_cli.py
  tests/test_singlepoint_cli.py
  tests/test_train_cli.py
  tests/utils.py
Labels: enhancement

#295 Save system name to info from file stem
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/single_point.py
  janus_core/helpers/utils.py
  tests/test_descriptors_cli.py
  tests/test_eos_cli.py
  tests/test_geomopt_cli.py
  tests/test_md_cli.py
  tests/test_singlepoint_cli.py
Labels: enhancement
