Repository stfc/janus-core, pull requests merged in 2025-02, with the labels that each got.

#402 Add progress bars to single point calculations
  janus_core/calculations/single_point.py
  janus_core/cli/singlepoint.py
Labels: enhancement

#407 Update mace
  README.md
  docs/source/getting_started/getting_started.rst
  janus_core/training/preprocess.py
  pyproject.toml
Labels: enhancement

#401 Specify Python version in dev docs
  docs/source/developer_guide/get_started.rst
Labels: documentation

#379 Add installation troubleshooting
  docs/source/user_guide/troubleshooting.rst
  pyproject.toml
Labels: documentation

#399 Test tutorials
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/publish-on-pypi.yml
  README.md
  docs/Makefile
  docs/source/conf.py
  docs/source/developer_guide/get_started.rst
  docs/source/index.rst
  docs/source/tutorials/eos.ipynb
  docs/source/tutorials/geom_opt.ipynb
  docs/source/tutorials/index.rst
  docs/source/tutorials/md.ipynb
  docs/source/tutorials/phonons.ipynb
  docs/source/tutorials/single_point.ipynb
  docs/source/user_guide/python.rst
  pyproject.toml
Labels: documentation, enhancement

#410 Add isotropic NPT MD
  janus_core/calculations/md.py
  janus_core/cli/md.py
  janus_core/helpers/janus_types.py
  tests/test_md.py
  tests/test_md_cli.py
Labels: enhancement

#416 Update authors
  CITATION.cff
  pyproject.toml
Labels: documentation

#304 add nequip support fixes #223
  README.md
  docs/source/getting_started/getting_started.rst
  janus_core/helpers/janus_types.py
  janus_core/helpers/mlip_calculators.py
  pyproject.toml
  tests/data/toluene.xyz
  tests/models/toluene.pth
  tests/test_mlip_calculators.py
  tests/test_single_point.py
Labels: enhancement

#429 Fix NPH and NVT_NH
  janus_core/calculations/md.py
  janus_core/cli/md.py
  tests/test_md.py
Labels: bug

#393 Add NEB
  README.md
  docs/source/apidoc/janus_core.rst
  docs/source/conf.py
  docs/source/user_guide/command_line.rst
  janus_core/calculations/eos.py
  janus_core/calculations/md.py
  janus_core/calculations/neb.py
  janus_core/calculations/phonons.py
  janus_core/cli/janus.py
  janus_core/cli/neb.py
  janus_core/cli/types.py
  janus_core/helpers/janus_types.py
  janus_core/helpers/utils.py
  pyproject.toml
  tests/data/LiFePO4-neb-band.xyz
  tests/data/LiFePO4_end.cif
  tests/data/LiFePO4_start.cif
  tests/data/LiFePO4_supercell-opt.cif
  tests/test_neb.py
  tests/test_neb_cli.py
Labels: enhancement

#414 Fix CSVR temperature ramp
  janus_core/calculations/md.py
  tests/test_md.py
  tests/test_md_cli.py
Labels: bug

#434 Add upper limit for sphinx
  pyproject.toml
Labels: bug, documentation

#435 Add NEB tutorial
  README.md
  docs/source/tutorials/index.rst
  docs/source/tutorials/neb.ipynb
  docs/source/user_guide/python.rst
Labels: documentation

#439 Remove cancel-in-progress for docs
  .github/workflows/docs.yml
  .github/workflows/publish-on-pypi.yml
Labels: bug, documentation

#438 Tidy neb
  janus_core/calculations/neb.py
  tests/test_neb.py
Labels: bug, enhancement

#437 Prevent temp steps less than timestep
  janus_core/calculations/md.py
  tests/test_md.py
  tests/test_md_cli.py
Labels: bug

#445 Add CI test against development versions
  .github/workflows/ci-dev.yml
Labels: testing

#415 Update torch
  .github/workflows/ci-dev.yml
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/mac.yml
  .github/workflows/publish-on-pypi.yml
  README.md
  docs/source/developer_guide/get_started.rst
  docs/source/developer_guide/tutorial.rst
  docs/source/getting_started/getting_started.rst
  docs/source/user_guide/index.rst
  docs/source/user_guide/installation.rst
  janus_core/helpers/mlip_calculators.py
  pyproject.toml
  tests/test_eos.py
  tests/test_mlip_calculators.py
  tests/test_single_point.py
  tests/test_utils.py
  tests/utils.py
Labels: documentation, enhancement

#452 Add file prefix options to singlepoint and geomopt
  docs/source/user_guide/command_line.rst
  janus_core/calculations/geom_opt.py
  janus_core/calculations/single_point.py
  janus_core/cli/geomopt.py
  janus_core/cli/singlepoint.py
  tests/test_geom_opt.py
  tests/test_geomopt_cli.py
Labels: enhancement

#453 Fix restarting simulations with a temperature ramp
  janus_core/calculations/md.py
  tests/test_md.py
Labels: bug
