Repository stfc/janus-core, pull requests merged in 2025-05, with the labels that each got.

#528 Rename model path
  docs/source/developer_guide/tutorial.rst
  docs/source/tutorials/python/eos.ipynb
  docs/source/tutorials/python/geom_opt.ipynb
  docs/source/tutorials/python/md.ipynb
  docs/source/tutorials/python/neb.ipynb
  docs/source/tutorials/python/phonons.ipynb
  docs/source/tutorials/python/single_point.ipynb
  docs/source/user_guide/command_line.rst
  docs/source/user_guide/python.rst
  janus_core/calculations/base.py
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/neb.py
  janus_core/calculations/phonons.py
  janus_core/calculations/single_point.py
  janus_core/cli/descriptors.py
  janus_core/cli/eos.py
  janus_core/cli/geomopt.py
  janus_core/cli/md.py
  janus_core/cli/neb.py
  janus_core/cli/phonons.py
  janus_core/cli/singlepoint.py
  janus_core/cli/types.py
  janus_core/helpers/mlip_calculators.py
  janus_core/helpers/struct_io.py
  tests/data/singlepoint_config.yml
  tests/test_correlator.py
  tests/test_descriptors.py
  tests/test_descriptors_cli.py
  tests/test_eos.py
  tests/test_eos_cli.py
  tests/test_geom_opt.py
  tests/test_geomopt_cli.py
  tests/test_md.py
  tests/test_md_cli.py
  tests/test_mlip_calculators.py
  tests/test_neb.py
  tests/test_neb_cli.py
  tests/test_phonons.py
  tests/test_phonons_cli.py
  tests/test_post_process.py
  tests/test_single_point.py
  tests/test_singlepoint_cli.py
  tests/test_utils.py
Labels: breaking

#532 Remove default arch
  README.md
  janus_core/calculations/base.py
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/neb.py
  janus_core/calculations/phonons.py
  janus_core/calculations/single_point.py
  janus_core/cli/descriptors.py
  janus_core/cli/eos.py
  janus_core/cli/geomopt.py
  janus_core/cli/md.py
  janus_core/cli/neb.py
  janus_core/cli/phonons.py
  janus_core/cli/singlepoint.py
  janus_core/cli/types.py
  janus_core/helpers/mlip_calculators.py
  janus_core/helpers/struct_io.py
  tests/data/NaCl-results.extxyz
  tests/test_descriptors.py
  tests/test_descriptors_cli.py
  tests/test_eos.py
  tests/test_eos_cli.py
  tests/test_geom_opt.py
  tests/test_geomopt_cli.py
  tests/test_md.py
  tests/test_md_cli.py
  tests/test_neb.py
  tests/test_neb_cli.py
  tests/test_phonons.py
  tests/test_phonons_cli.py
  tests/test_post_process.py
  tests/test_single_point.py
  tests/test_singlepoint_cli.py
Labels: enhancement, breaking

#537 Fix building documentation
  pyproject.toml
Labels: bug, documentation, priority

#534 Update tutorials
  docs/source/tutorials/cli/geomopt.ipynb
  docs/source/tutorials/cli/md.ipynb
  docs/source/tutorials/cli/singlepoint.ipynb
Labels: bug, testing

#535 Fix documentation warnings
  docs/source/conf.py
Labels: bug, documentation

#538 Update mace
  pyproject.toml
  tests/data/mlip_preprocess.yml
  tests/data/mlip_preprocess_stats.yml
Labels: dependencies

#541 Fix typer
  pyproject.toml
Labels: bug, priority, dependencies

#539 Remove DGL MLIPs for Windows
  .github/workflows/windows.yml
  README.md
  docs/source/getting_started/getting_started.rst
  docs/source/user_guide/installation.rst
  pyproject.toml
Labels: bug, testing

#540 Update Orb
  pyproject.toml
Labels: dependencies

#505 Check exact and fuzzy matches in Stats
  janus_core/helpers/stats.py
  tests/test_stats.py
Labels: bug, enhancement

#542 Fix writing optimisation trajectory to new directory
  janus_core/calculations/geom_opt.py
  tests/test_geom_opt.py
Labels: bug

#545 Fix docs warnings
  .github/workflows/ci.yml
  docs/source/user_guide/installation.rst
Labels: documentation

#421 Add fairchem architectures
  .github/workflows/ci.yml
  .github/workflows/mac.yml
  .github/workflows/windows.yml
  README.md
  docs/source/getting_started/getting_started.rst
  janus_core/helpers/janus_types.py
  janus_core/helpers/mlip_calculators.py
  pyproject.toml
  tests/test_mlip_calculators.py
  tests/test_single_point.py
  tests/utils.py
Labels: enhancement

#546 Rename filter
  docs/source/tutorials/cli/geomopt.ipynb
  docs/source/tutorials/python/eos.ipynb
  docs/source/tutorials/python/geom_opt.ipynb
  docs/source/tutorials/python/phonons.ipynb
  janus_core/calculations/geom_opt.py
  janus_core/calculations/neb.py
  janus_core/cli/geomopt.py
  janus_core/cli/utils.py
  tests/test_geom_opt.py
  tests/test_geomopt_cli.py
Labels: breaking
