Repository stfc/janus-core, pull requests merged in 2025-03, with the labels that each got.

#459 Remove M3GNet from tutorials
  docs/source/tutorials/eos.ipynb
  docs/source/tutorials/geom_opt.ipynb
  docs/source/tutorials/phonons.ipynb
  docs/source/tutorials/single_point.ipynb
Labels: bug, documentation

#458 Fix NEB
  janus_core/calculations/neb.py
  tests/test_neb.py
  tests/test_neb_cli.py
Labels: bug

#427 add mattersim calculator fixes #425
  .github/workflows/ci.yml
  .github/workflows/mac.yml
  README.md
  docs/source/getting_started/getting_started.rst
  janus_core/helpers/janus_types.py
  janus_core/helpers/mlip_calculators.py
  pyproject.toml
  tests/test_mlip_calculators.py
  tests/test_single_point.py
  tests/utils.py
Labels: enhancement

#467 Add progress bar for descriptors
  janus_core/calculations/descriptors.py
  janus_core/cli/descriptors.py
Labels: enhancement

#468 Fix duplicate stats headers
  janus_core/calculations/md.py
Labels: bug

#463 Save input configuration
  janus_core/cli/descriptors.py
  janus_core/cli/eos.py
  janus_core/cli/geomopt.py
  janus_core/cli/md.py
  janus_core/cli/neb.py
  janus_core/cli/phonons.py
  janus_core/cli/preprocess.py
  janus_core/cli/singlepoint.py
  janus_core/cli/train.py
  janus_core/cli/utils.py
  tests/test_descriptors_cli.py
  tests/test_eos_cli.py
  tests/test_geomopt_cli.py
  tests/test_md_cli.py
  tests/test_neb_cli.py
  tests/test_phonons_cli.py
  tests/test_preprocess_cli.py
  tests/test_singlepoint_cli.py
  tests/test_train_cli.py
Labels: enhancement

#462 Add default output directory
  docs/source/user_guide/command_line.rst
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/md.py
  janus_core/calculations/neb.py
  janus_core/calculations/phonons.py
  janus_core/cli/descriptors.py
  janus_core/cli/eos.py
  janus_core/cli/geomopt.py
  janus_core/cli/md.py
  janus_core/cli/neb.py
  janus_core/cli/phonons.py
  janus_core/cli/preprocess.py
  janus_core/cli/singlepoint.py
  janus_core/cli/train.py
  janus_core/cli/types.py
  janus_core/cli/utils.py
  janus_core/helpers/log.py
  janus_core/helpers/struct_io.py
  janus_core/helpers/utils.py
  janus_core/processing/post_process.py
  tests/test_descriptors_cli.py
  tests/test_eos_cli.py
  tests/test_filenamemixin.py
  tests/test_geom_opt.py
  tests/test_geomopt_cli.py
  tests/test_md.py
  tests/test_md_cli.py
  tests/test_neb.py
  tests/test_neb_cli.py
  tests/test_phonons.py
  tests/test_phonons_cli.py
  tests/test_post_process.py
  tests/test_preprocess_cli.py
  tests/test_single_point.py
  tests/test_singlepoint_cli.py
  tests/test_train_cli.py
Labels: enhancement

#454 List outputs
  janus_core/calculations/base.py
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/neb.py
  janus_core/calculations/phonons.py
  janus_core/calculations/single_point.py
  janus_core/cli/descriptors.py
  janus_core/cli/eos.py
  janus_core/cli/geomopt.py
  janus_core/cli/md.py
  janus_core/cli/neb.py
  janus_core/cli/phonons.py
  janus_core/cli/preprocess.py
  janus_core/cli/singlepoint.py
  janus_core/cli/train.py
  janus_core/cli/utils.py
  janus_core/helpers/utils.py
  tests/test_descriptors_cli.py
  tests/test_eos_cli.py
  tests/test_filenamemixin.py
  tests/test_geom_opt.py
  tests/test_geomopt_cli.py
  tests/test_log.py
  tests/test_md_cli.py
  tests/test_neb_cli.py
  tests/test_phonons_cli.py
  tests/test_preprocess_cli.py
  tests/test_singlepoint_cli.py
  tests/test_train_cli.py
  tests/utils.py
Labels: enhancement

#388 Add Correlator CLI and defaults
  docs/source/user_guide/command_line.rst
  janus_core/calculations/md.py
  janus_core/cli/md.py
  janus_core/cli/types.py
  janus_core/cli/utils.py
  janus_core/helpers/janus_types.py
  janus_core/processing/correlator.py
  janus_core/processing/observables.py
  tests/test_correlator.py
  tests/test_md_cli.py
  tests/test_utils.py
Labels: enhancement

#475 Revert "bump version for release 0.7.5"
  pyproject.toml
Labels: bug

#474 Fix typo
  janus_core/calculations/neb.py
Labels: documentation

#476 Fix reading output in tutorial
  docs/source/tutorials/md.ipynb
Labels: bug, documentation

#478 Add singlepoint and geomopt CLI tutorials
  docs/source/tutorials/cli/geomopt.ipynb
  docs/source/tutorials/cli/singlepoint.ipynb
Labels: documentation

#492 Fix CLI tutorials for Colab
  docs/source/tutorials/cli/geomopt.ipynb
  docs/source/tutorials/cli/md.ipynb
  docs/source/tutorials/cli/neb.ipynb
  docs/source/tutorials/cli/phonons.ipynb
  docs/source/tutorials/cli/singlepoint.ipynb
Labels: bug, documentation

#491 Update MACE
  pyproject.toml
Labels: dependencies

#493 Use click choices in CLI
  janus_core/cli/eos.py
  janus_core/cli/md.py
  janus_core/cli/singlepoint.py
  janus_core/cli/types.py
Labels: documentation, enhancement
