Repository stfc/janus-core, pull requests merged in 2025-04, with the labels that each got.

#500 Generate release notes automatically
  .github/workflows/publish-on-pypi.yml
Labels: documentation

#502 Use pyproject authors for copyright
  docs/source/conf.py
Labels: documentation

#503 Fix Python tutorials for Colab
  docs/source/tutorials/python/eos.ipynb
  docs/source/tutorials/python/geom_opt.ipynb
  docs/source/tutorials/python/md.ipynb
  docs/source/tutorials/python/neb.ipynb
  docs/source/tutorials/python/phonons.ipynb
  docs/source/tutorials/python/single_point.ipynb
Labels: bug, documentation

#501 Build docs only on release
  .github/workflows/docs.yml
Labels: documentation

#496 Add Windows CI
  .github/workflows/windows.yml
  docs/source/getting_started/getting_started.rst
  janus_core/helpers/log.py
  pyproject.toml
  tests/test_geomopt_cli.py
  tests/test_md_cli.py
  tests/test_phonons.py
  tests/test_phonons_cli.py
  tests/test_train_cli.py
  tests/utils.py
Labels: testing

#426 add grace calculator, clarify gpu/cpu fixes #408
  README.md
  conftest.py
  docs/source/getting_started/getting_started.rst
  janus_core/helpers/janus_types.py
  janus_core/helpers/mlip_calculators.py
  pyproject.toml
  tests/test_mlip_calculators.py
  tests/test_single_point.py
  tests/utils.py
Labels: enhancement

#508 Update Orb
  janus_core/helpers/mlip_calculators.py
  pyproject.toml
  tests/test_single_point.py
Labels: dependencies

#509 Fix docs status badge
  README.md
Labels: bug, documentation

#513 Fix ASE
  pyproject.toml
  tests/test_md.py
  tests/test_md_cli.py
Labels: bug, testing, priority, dependencies

#511 Catch connection error for GRACE
  tests/test_mlip_calculators.py
  tests/test_single_point.py
Labels: bug, testing

#514 Fix tox
  pyproject.toml
  tox.ini
Labels: bug, testing

#520 Fix codecarbon
  pyproject.toml
  tests/test_log.py
Labels: bug, testing

#516 Fix catching BadZipFile
  tests/test_mlip_calculators.py
Labels: bug, testing

#524 Update README tutorial links (source files moved)
  README.md
Labels: documentation

#527 Fix error catching in tests
  tests/test_mlip_calculators.py
  tests/test_single_point.py
Labels: bug, testing

#530 Tidy NEB error handling and tests
  janus_core/calculations/neb.py
  janus_core/cli/neb.py
  tests/test_neb.py
Labels: enhancement
