Repository stfc/janus-core, pull requests merged in 2025-01, with the labels that each got.

#376 Implement temporary fix for CI
  .github/workflows/ci.yml
Labels: bug, testing, priority

#366 Add Bussi thermostat
  janus_core/calculations/md.py
  janus_core/cli/md.py
  janus_core/helpers/janus_types.py
  tests/test_md.py
  tests/test_md_cli.py
Labels: enhancement

#334 Test mac on self-hosted runner
  .github/workflows/mac.yml
  docs/source/developer_guide/ci.rst
  docs/source/developer_guide/index.rst
Labels: testing

#371 Improve logging and carbon tracking consistency
  docs/source/user_guide/index.rst
  docs/source/user_guide/troubleshooting.rst
  janus_core/calculations/base.py
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/phonons.py
  janus_core/calculations/single_point.py
  janus_core/helpers/log.py
  janus_core/helpers/utils.py
  janus_core/training/preprocess.py
  janus_core/training/train.py
  tests/test_log.py
Labels: enhancement

#369 Comment correlation algorithm, remove flattening of Velocity observable
  janus_core/processing/correlator.py
  janus_core/processing/observables.py
Labels: documentation

#378 Add units
  janus_core/calculations/base.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/phonons.py
  janus_core/calculations/single_point.py
  janus_core/processing/observables.py
  tests/test_geomopt_cli.py
  tests/test_md_cli.py
  tests/test_singlepoint_cli.py
Labels: enhancement

#382 Fix release
  .github/workflows/publish-on-pypi.yml
  pyproject.toml
Labels: bug, priority

#383 Test and document external calculators
  docs/source/user_guide/python.rst
  tests/test_ase_calculators.py
Labels: documentation

#384 Update MLIPs
  README.md
  docs/source/getting_started/getting_started.rst
  pyproject.toml
Labels: enhancement

#350 Autodoc typehints
  docs/source/conf.py
  janus_core/calculations/base.py
  janus_core/calculations/descriptors.py
  janus_core/calculations/eos.py
  janus_core/calculations/geom_opt.py
  janus_core/calculations/md.py
  janus_core/calculations/phonons.py
  janus_core/calculations/single_point.py
  janus_core/cli/descriptors.py
  janus_core/cli/eos.py
  janus_core/cli/geomopt.py
  janus_core/cli/janus.py
  janus_core/cli/md.py
  janus_core/cli/phonons.py
  janus_core/cli/preprocess.py
  janus_core/cli/singlepoint.py
  janus_core/cli/train.py
  janus_core/cli/types.py
  janus_core/cli/utils.py
  janus_core/helpers/log.py
  janus_core/helpers/mlip_calculators.py
  janus_core/helpers/stats.py
  janus_core/helpers/struct_io.py
  janus_core/helpers/utils.py
  janus_core/processing/correlator.py
  janus_core/processing/observables.py
  janus_core/processing/post_process.py
  janus_core/processing/symmetry.py
  janus_core/training/preprocess.py
  janus_core/training/train.py
  pyproject.toml
  tests/test_preprocess_cli.py
  tests/test_train_cli.py
  tests/utils.py
Labels: documentation

#392 Update ruff
  .pre-commit-config.yaml
  janus_core/calculations/phonons.py
  janus_core/helpers/mlip_calculators.py
  janus_core/processing/observables.py
  pyproject.toml
Labels: enhancement

#394 Add ipykernel dev dependency
  pyproject.toml
Labels: enhancement

#390 Update docs
  README.md
  docs/source/getting_started/getting_started.rst
Labels: documentation

#396 Add uv description
  docs/source/developer_guide/get_started.rst
Labels: documentation
