Repository stfc/janus-core, pull requests merged in 2025-06, with the labels that each got.

#555 Update dpa
  pyproject.toml
Labels: dependencies

#526 Added plumed for metadynamics simulations
  .github/workflows/ci.yml
  .github/workflows/mac.yml
  .github/workflows/windows.yml
  README.md
  docs/source/getting_started/getting_started.rst
  docs/source/user_guide/command_line.rst
  docs/source/user_guide/installation.rst
  janus_core/calculations/md.py
  janus_core/cli/md.py
  pyproject.toml
  tests/data/isomer.xyz
  tests/data/plumed.dat
  tests/test_md.py
  tests/test_md_plumed.py
Labels: enhancement

#560 Update docs
  docs/source/conf.py
Labels: documentation

#561 Update deps
  .github/workflows/ci-dev.yml
  .github/workflows/ci.yml
  .github/workflows/mac.yml
  .github/workflows/publish-on-pypi.yml
  .github/workflows/windows.yml
  .pre-commit-config.yaml
  janus_core/calculations/md.py
  pyproject.toml
Labels: dependencies

#562 Add warning for deprecated CLI parameters
  janus_core/cli/geomopt.py
  janus_core/cli/types.py
  janus_core/cli/utils.py
Labels: enhancement

#565 Update minimize_kwargs CLI help
  janus_core/cli/types.py
Labels: documentation
